//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProje.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class Muzik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Muzik()
        {
            this.alet_marka = new HashSet<alet_marka>();
            this.garantiBilgisi = new HashSet<garantiBilgisi>();
            this.StokTakip = new HashSet<StokTakip>();
        }
    
        public int aletId { get; set; }
        public Nullable<int> kategoriId { get; set; }
        [Required(ErrorMessage = "Alet adını giriniz")]
        [DisplayName("Alet Adı")]
        public string aletAdi { get; set; }
        [Required(ErrorMessage = "Satış adet sayısını giriniz")]
     
        [DisplayName("Satılan Alet Sayısı")]
        public Nullable<int> satışAdetSayisi { get; set; }
        [Required(ErrorMessage = "Alet fiyatını giriniz")]
        [DisplayName("Alet Fiyatı")]
        public Nullable<decimal> aletFiyati { get; set; }

        public Nullable<int> garantiId { get; set; }
        public Nullable<int> stokId { get; set; }
        public Nullable<int> markaId { get; set; }
    
        public virtual alet_kategori alet_kategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alet_marka> alet_marka { get; set; }
        public virtual alet_marka alet_marka1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<garantiBilgisi> garantiBilgisi { get; set; }
        public virtual garantiBilgisi garantiBilgisi1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StokTakip> StokTakip { get; set; }
    }
}
