//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProje.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MuzikAtolyesiEntities6 : DbContext
    {
        public MuzikAtolyesiEntities6()
            : base("name=MuzikAtolyesiEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alet_kategori> alet_kategori { get; set; }
        public virtual DbSet<alet_marka> alet_marka { get; set; }
        public virtual DbSet<garantiBilgisi> garantiBilgisi { get; set; }
        public virtual DbSet<Muzik> Muzik { get; set; }
        public virtual DbSet<StokTakip> StokTakip { get; set; }
        public virtual DbSet<UserProfile> UserProfile { get; set; }
        public virtual DbSet<Uyeler> Uyeler { get; set; }
    }
}
