//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Muzikler
    {
        public int aletId { get; set; }
        public Nullable<int> kategoriId { get; set; }
        public string aletAdi { get; set; }
    
        public virtual AletKategori AletKategori { get; set; }
    }
}
