//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProje.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class StokTakip
    {
        public int stokId { get; set; }
        [Required(ErrorMessage = "Stok adet sayýsýný giriniz")]
       
        [DisplayName("Stok Sayýsý")]
        public Nullable<int> stokAdeti { get; set; }
        public Nullable<int> aletId { get; set; }
    
        public virtual Muzik Muzik { get; set; }
    }
}
