//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProje.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class UserProfile
    {
        public int UserId { get; set; }
        [Required(ErrorMessage = "isminizi giriniz")]
      
        [DisplayName("Ýsim")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "þifrenizi giriniz")]
        [DataType(DataType.Password)]
        [MinLength(6, ErrorMessage = "Þifreniz 6 karakterden küçük olmamalý.")]
        [DisplayName("Þifre")]
        public string Password { get; set; }
    }
}
