//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProje.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class Uyeler
    {
        public int UyeId { get; set; }
       
       
       
        public string UyeAdi { get; set; }
        public string UyeSoyadi { get; set; }
        public string UyeTc { get; set; }
        public Nullable<decimal> UyeTel { get; set; }
        public string UyeAdres { get; set; }
    }
}
